spring.application.name=devconnector-api
# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

# This ensures the filter handles the token BEFORE the file is processed
spring.servlet.multipart.resolve-lazily=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

