spring.application.name=devconnector-api
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/devconnector
spring.datasource.username=postgres
spring.datasource.password=9196

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

# This ensures the filter handles the token BEFORE the file is processed
spring.servlet.multipart.resolve-lazily=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true